spring:
  application:
    name: cyclic-action
  datasource:
    url: ${DB_URL}

excel-management:
  skip-lines:
    action-history: 5
    actual-avg-sales: 6
  header-row-index:
    action-history: 4
    actual-avg-sales: 5
  input:
    action-history: input/Акційна історія.xlsx
    actual-avg-sales: input/Актуальні СДП.xlsx
  output:
    action-history: output/

cyclic-action:
  start-date: ${START_DATE}
  end-date: ${END_DATE}
